# Generated by Django 2.1 on 2019-12-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_i_can_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='I_can_program',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='year_in_school',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=2),
            preserve_default=False,
        ),
    ]
